import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import HeaderPage from "./components/header";
import MarkQuee from "./components/MarkQuee";
import Footer from "./components/Footer";

const notoSerifBengali = Noto_Serif_Bengali({
  subsets: ["latin", 'bengali'],
});


export const metadata: Metadata = {
  title: "News Bangla 24",
  description: "Generated by News Bangla 24",
  icons: {
    icon:'/logo.webp'
  }
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme='light'
      className={`${notoSerifBengali.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <HeaderPage></HeaderPage>
        <MarkQuee></MarkQuee>
        <main >
          {children}
        </main>
        <Footer></Footer>
      </body>
    </html>
  );
}
